### YamlMime:PythonClass
uid: adal.adal_error.AdalError
name: AdalError
fullName: adal.adal_error.AdalError
module: adal.adal_error
inheritances:
- builtins.Exception
constructor:
  syntax: AdalError(error_msg, error_response=None)
  parameters:
  - name: error_msg
  - name: error_response
    defaultValue: None
methods:
- uid: adal.adal_error.AdalError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: adal.adal_error.AdalError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: adal.adal_error.AdalError.args
  name: args
