### YamlMime:PythonClass
uid: azure.datalake.store.exceptions.DatalakeBadOffsetException
name: DatalakeBadOffsetException
fullName: azure.datalake.store.exceptions.DatalakeBadOffsetException
module: azure.datalake.store.exceptions
inheritances:
- builtins.OSError
constructor:
  syntax: DatalakeBadOffsetException()
methods:
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.args
  name: args
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.characters_written
  name: characters_written
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.errno
  name: errno
  summary: POSIX exception code
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.filename
  name: filename
  summary: exception filename
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.filename2
  name: filename2
  summary: second exception filename
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.strerror
  name: strerror
  summary: exception strerror
- uid: azure.datalake.store.exceptions.DatalakeBadOffsetException.winerror
  name: winerror
  summary: Win32 exception code
