### YamlMime:PythonClass
uid: azure.datalake.store.exceptions.DatalakeRESTException
name: DatalakeRESTException
fullName: azure.datalake.store.exceptions.DatalakeRESTException
module: azure.datalake.store.exceptions
inheritances:
- builtins.OSError
constructor:
  syntax: DatalakeRESTException()
methods:
- uid: azure.datalake.store.exceptions.DatalakeRESTException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.datalake.store.exceptions.DatalakeRESTException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.datalake.store.exceptions.DatalakeRESTException.args
  name: args
- uid: azure.datalake.store.exceptions.DatalakeRESTException.characters_written
  name: characters_written
- uid: azure.datalake.store.exceptions.DatalakeRESTException.errno
  name: errno
  summary: POSIX exception code
- uid: azure.datalake.store.exceptions.DatalakeRESTException.filename
  name: filename
  summary: exception filename
- uid: azure.datalake.store.exceptions.DatalakeRESTException.filename2
  name: filename2
  summary: second exception filename
- uid: azure.datalake.store.exceptions.DatalakeRESTException.strerror
  name: strerror
  summary: exception strerror
- uid: azure.datalake.store.exceptions.DatalakeRESTException.winerror
  name: winerror
  summary: Win32 exception code
