### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.ParamValueNotExistsError
name: ParamValueNotExistsError
fullName: azure.ai.ml.exceptions.ParamValueNotExistsError
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.KeywordError
summary: Exception raised when items in non_pipeline_inputs not in keyword parameters
  in dynamic functions.
constructor:
  syntax: ParamValueNotExistsError(func_name, keywords)
  parameters:
  - name: func_name
  - name: keywords
methods:
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.args
  name: args
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.error_category
  name: error_category
  summary: Return the error category.
  return:
    description: The error category.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorCategory>
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.no_personal_data_message
  name: no_personal_data_message
  summary: Return the error message with no personal data.
  return:
    description: No personal data error message.
    types:
    - <xref:str>
- uid: azure.ai.ml.exceptions.ParamValueNotExistsError.target
  name: target
  summary: Return the error target.
  return:
    description: The error target.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorTarget>
