### YamlMime:PythonClass
uid: azure.core.exceptions.StreamConsumedError
name: StreamConsumedError
fullName: azure.core.exceptions.StreamConsumedError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.AzureError
summary: 'Error thrown if you try to access the stream of a response once consumed.


  It is thrown if you try to read / stream an ~azure.core.rest.HttpResponse or

  ~azure.core.rest.AsyncHttpResponse once the response''s stream has been consumed.'
constructor:
  syntax: StreamConsumedError(response)
  parameters:
  - name: response
    description: The response that triggered the exception.
    isRequired: true
    types:
    - <xref:azure.core.rest.HttpResponse>
    - <xref:azure.core.rest.AsyncHttpResponse>
methods:
- uid: azure.core.exceptions.StreamConsumedError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.StreamConsumedError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.StreamConsumedError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.StreamConsumedError.args
  name: args
