### YamlMime:PythonClass
uid: msrestazure.azure_exceptions.CloudError
name: CloudError
fullName: msrestazure.azure_exceptions.CloudError
module: msrestazure.azure_exceptions
inheritances:
- msrest.exceptions.ClientException
summary: 'ClientError, exception raised for failed Azure REST call.

  Will attempt to deserialize response into meaningful error

  data.'
constructor:
  syntax: CloudError(response, error=None, *args, **kwargs)
  parameters:
  - name: response
    description: Response object.
    isRequired: true
    types:
    - <xref:requests.Response>
  - name: error
    description: Optional error message.
    defaultValue: None
    types:
    - <xref:str>
methods:
- uid: msrestazure.azure_exceptions.CloudError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: msrestazure.azure_exceptions.CloudError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: msrestazure.azure_exceptions.CloudError.args
  name: args
